### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by toxeus**

### CODE REVIEW

**Comment by toxeus** [comment]
@grealish ping

**Comment by grealish** [comment]
Makes sence to factor out the otuser, lets merge this +1

**Comment by grealish** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mhamrle** [comment]
:+1:

**Comment by grealish** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
